services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_NAME
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_DATABASE
    web:
        image: node:18
        depends_on:
            - postgres
        volumes:
            - .:/app
        working_dir: /app
        command: sh -c 'npm run sync && npm run dev'
        ports:
            - "3000:3000"
            - "4444:4444"
        environment:
            - APP_URL
            - WSL_URL
            - NODE_ENV=development
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}
            - SOCKET_PORT=4444
# services:
#     postgres:
#         env_file:
#             - .env
#         image: postgres
#         ports:
#             - 5432:5432
#     web:
#         build:
#             context: ./
#             target: runner
#         volumes:
#             - .:/app
#         command: npm run dev
#         ports:
#             - "3000:3000"
#         environment:
#             NODE_ENV: development
