services:
    postgres:
        env_file:
            - .env.development
    prisma-studio:
        image: node:18
        depends_on:
            - postgres
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "5555:5555"
        env_file:
            - .env.development
        command: sh -c 'npm install && npx dotenv -e ./../.env.development -- npm run studio --workspace=notecraft-schema'
        # labels:
        #     - "traefik.enable=true"
        #     # - "traefik.http.routers.ws.rule=Host(`${NEXT_PUBLIC_WEB_APP_URL}`) && Headers(`upgrade`, `websocket`) && !PathPrefix(`/_next`)"
        #     - "traefik.http.routers.ws.rule=Host(`studio.localhost`)"
    reverse-proxy:
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
    app:
        image: node:18
        env_file:
            - .env.development
        working_dir: /app
        command: sh -c 'npm install && npm run syncDangerous --workspace=notecraft-schema && npm run dev --workspace=notecraft-app'
        volumes:
            - .:/app

    ws:
        image: node:18
        env_file:
            - .env.development
        command: sh -c 'npm install && npm run dev --workspace=notecraft-ws'
        working_dir: /app
        volumes:
            - .:/app
