services:
    app:
        image: node:18
        env_file:
            - .env.development
        command: sh -c 'npm install && npm run syncDangerous --workspace=notecraft-schema && npm run dev --workspace=notecraft-app'
        volumes:
            - .:/app

    ws:
        image: node:18
        env_file:
            - .env.development
        command: sh -c 'npm install && npm run dev --workspace=notecraft-ws'
        volumes:
            - .:/app
