services:
    app:
        build:
            context: .
            dockerfile: notesmith-app/Dockerfile

    ws:
        build:
            context: .
            dockerfile: notesmith-ws/Dockerfile
