version: "3"

services:
    postgres:
        image: postgres
        expose:
            - "5432"
        environment:
            - POSTGRES_NAME
            - POSTGRES_USERNAME
            - POSTGRES_PASSWORD
            - POSTGRES_DATABASE
    reverse-proxy:
        # The official v2 Traefik docker image
        image: traefik:v2.10
        # Enables the web UI and tells Traefik to listen to docker
        labels:
            # Dashboard
            - "traefik.enable=true"
            - "traefik.http.routers.dashboard.rule=Host(`${NEXT_PUBLIC_WEB_APP_URL}`) && PathPrefix(`/dashboard`)"
            - "traefik.http.routers.dashboard.entrypoints=websecure"
            - "traefik.http.routers.dashboard.service=api@internal"
        ports:
            # The HTTP port
            - "80:80"
            - "443:443"
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
        volumes:
            # So that Traefik can listen to the Docker events
            - /var/run/docker.sock:/var/run/docker.sock
    redis:
        image: redis:7
        container_name: ${REDIS_HOST}
    app:
        depends_on:
            - postgres
            - redis
        # volumes:
        #     - ./notecraft-app:/app
        #     - ./prisma:/app/prisma
        #     - ./notecraft-common:/app/notecraft-common
        # working_dir: /app
        # By default, Traefik uses the first exposed port of a container
        expose:
            - "3000"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.app.rule=Host(`${NEXT_PUBLIC_WEB_APP_URL}`) && !Headers(`upgrade`, `websocket`)"
            # - "traefik.http.routers.app.rule=Host(`${NEXT_PUBLIC_WEB_APP_URL}`)"
    ws:
        depends_on:
            - redis
        # volumes:
        #     - ./notecraft-ws:/app
        #     - ./notecraft-common:/app/notecraft-common
        # working_dir: /app
        expose:
            - "4444"
        labels:
            - "traefik.enable=true"
            # - "traefik.http.routers.ws.rule=Host(`${NEXT_PUBLIC_WEB_APP_URL}`) && Headers(`upgrade`, `websocket`) && !PathPrefix(`/_next`)"
            - "traefik.http.routers.ws.rule=Host(`${NEXT_PUBLIC_WEB_APP_URL}`) && Headers(`upgrade`, `websocket`) && !PathPrefix(`/_next`)"
