services:
    app:
        # command: sh -c 'npm install && npm run syncDangerous && npm run dev'
        build:
            context: .
            dockerfile: notesmith-app/Dockerfile

    ws:
        build:
            context: .
            dockerfile: notesmith-ws/Dockerfile
        # command: sh -c 'npm install && npm run dev'
