services:
    postgres:
        env_file:
            - .env.development
    reverse-proxy:
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
    app:
        image: node:18
        env_file:
            - .env.development
        command: sh -c 'npm install && npm run syncDangerous --workspace=notecraft-schema && npm run dev --workspace=notecraft-app'
        volumes:
            - .:/app

    ws:
        image: node:18
        env_file:
            - .env.development
        command: sh -c 'npm install && npm run dev --workspace=notecraft-ws'
        volumes:
            - .:/app
