services:
    app:
        image: node:18
        command: sh -c 'npm install && npm run syncDangerous --workspace=notesmith-schema && npm run dev --workspace=notesmith-app'
        volumes:
            - .:/app

    ws:
        image: node:18
        command: sh -c 'npm install && npm run dev --workspace=notesmith-ws'
        volumes:
            - .:/app
